[fluvel]
production = false

[app]
name = "MyFluvelApp"
display_name = "My App for Development UI's"
desktop_filename = "com.robotid.myfluvelapp"
version = "0.1.0"
organization = "Robotid"
domain = "example.com"
icon = "path/to/icon.png"
licence = "LGPLv3"
copyright = "Â© 2025 Robotid"

[ui]
theme = "bootstrap"

[window]
title = "MyApp"
size = [900, 600]
